esphome:
  name: boiler
  includes:
  - custom_component.h

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  password: "6e19f7fe46de7e5291f2077c9a8fbf55"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gollum Fallback Hotspot"
    password: "xWC7YZPWeQBO"

captive_portal:

web_server:
  port: 80
  
mqtt:
  broker: 192.168.1.23
  username: homeassistant
  password: eiThai6ooHee3eij1aef4eequoo6buCeeYuu0Ew0Jo8sei4eey0ou1gei4phai7U


sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new CustomComponent();
    App.register_component(my_custom_sensor);
    return {my_custom_sensor->boiler_mode, my_custom_sensor->boiler_setpoint};
   
  sensors:
  - name: "Boiler Mode"
  - name: "Boiler Setpoint"

